package syslimit

import (
	"context"
	"log/slog"
	"os"
	"os/exec"
	"strings"
)

// LimitsConfApplier now acts as a noop applier and removes previously
type LimitsConfApplier struct {
	logger      *slog.Logger
	templateDir string
}

// NewLimitsConfApplier creates a new instance.
func NewLimitsConfApplier(logger *slog.Logger, templateDir string) *LimitsConfApplier {
	return &LimitsConfApplier{
		logger:      logger,
		templateDir: templateDir,
	}
}

// Apply removes any prior limit configuration generated by tcsss and exits.
func (lca *LimitsConfApplier) Apply(ctx context.Context) error {
	removed, reexec := lca.cleanupGeneratedFiles(ctx)
	if lca.logger != nil {
		lca.logger.Info("limit management disabled; no limits applied",
			slog.Int("removed_files", removed),
			slog.Bool("systemd_reexec", reexec))
	}
	return nil
}

// reloadSystemd executes systemctl daemon-reexec to apply changes immediately.
func (lca *LimitsConfApplier) reloadSystemd(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "systemctl", "daemon-reexec")
	if _, err := cmd.CombinedOutput(); err != nil {
		return err
	}
	return nil
}

// cleanupGeneratedFiles removes previously generated limit configs.
// It only removes files that contain the tcsss markers to avoid deleting user-managed files.
func (lca *LimitsConfApplier) cleanupGeneratedFiles(ctx context.Context) (removedFiles int, systemdReexec bool) {
	files := []struct {
		path      string
		marker    string
		isSystemd bool
	}{
		{path: "/etc/security/limits.conf", marker: "# Generated by tcsss - System resource limits", isSystemd: false},
		{path: "/etc/systemd/system.conf", marker: "# Generated by tcsss - systemd default resource limits", isSystemd: true},
	}

	for _, f := range files {
		select {
		case <-ctx.Done():
			return removedFiles, systemdReexec
		default:
		}

		data, err := os.ReadFile(f.path)
		if err != nil {
			continue
		}
		if !strings.Contains(string(data), f.marker) {
			continue
		}
		if err := os.Remove(f.path); err != nil {
			if lca.logger != nil {
				lca.logger.Warn("failed to remove generated limit config",
					slog.String("file", f.path),
					slog.String("error", err.Error()))
			}
			continue
		}
		removedFiles++
		if lca.logger != nil {
			lca.logger.Info("removed generated limit config", slog.String("file", f.path))
		}

		// If systemd manager config was removed, reexec to drop previous limits.
		if f.isSystemd {
			if err := lca.reloadSystemd(ctx); err != nil {
				if lca.logger != nil {
					lca.logger.Warn("systemd reload after limit cleanup failed",
						slog.String("error", err.Error()),
						slog.String("action", "run 'systemctl daemon-reexec' manually"))
				}
			} else {
				systemdReexec = true
				if lca.logger != nil {
					lca.logger.Info("systemd reloaded after removing generated limits")
				}
			}
		}
	}

	return removedFiles, systemdReexec
}
